name: 'Setup Tor environment'
description: 'Setup a Tor environment and add it to the PATH'
author: 'warcbot'
branding:
  color: 'gray-dark'
  icon: 'activity'
inputs: 
  tor-version:
    description: 'The Tor version to download (if necessary) and use. Examples: 0.4.5.7, 0.4.5-rc7'
    default: '0.4.5.7'
  stable:
    description: 'Whether to download only stable versions'
    default: 'false'
  daemon:
    description: 'Run Tor as daemon program'
    default: 'false'
  port:
    description: 'Tor socks port'
    default: '9050'
  token:
    description: Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
